# Generated by Django 3.0 on 2020-11-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20201126_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='url',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
